/**
  * Created by Neta on 09/04/2016.
  */
object Ethnicity {

  def description2ethnicity(description: String): String = {

    val russianlist = List(
      ("""i am russian""".r),
      ("""im russian""".r),
      ("""i'm russian""".r),
      ("""i am a russian""".r),
      ("""im a russian""".r),
      ("""i'm a russian""".r),
      ("""i am a proud russian""".r),
      ("""im a proud russian""".r),
      ("""i'm a proud russian""".r),
      ("""proud russian""".r),
      ("""years old russian""".r)
    )

    val mexicanlist = List (
      ("""i am mexican""".r),
      ("""im mexican""".r),
      ("""i'm mexican""".r),
      ("""i am a mexican""".r),
      ("""im a mexican""".r),
      ("""i'm a mexican""".r),
      ("""i am a proud mexican""".r),
      ("""im a proud mexican""".r),
      ("""i'm a proud mexican""".r),
      ("""proud mexican""".r),
      ("""years old mexican""".r),
      ("""i am from mexico""".r),
      ("""i'm from mexico""".r),
      ("""im from mexico""".r)
    )

    val americanlist = List (
      ("""i am american""".r),
      ("""im american""".r),
      ("""i'm american""".r),
      ("""i am a american""".r),
      ("""im a american""".r),
      ("""i'm a american""".r),
      ("""i am a proud american""".r),
      ("""im a proud american""".r),
      ("""i'm a proud american""".r),
      ("""proud american""".r),
      ("""years old american""".r),
      ("""i am from america""".r),
      ("""im from america""".r),
      ("""i'm from america""".r),
      ("""im from the USA""".r),
      ("""i'm from the USA""".r),
      ("""i am from the USA""".r),
      ("""i am new yorker""".r),
      ("""im new yorker""".r),
      ("""i'm new yorker""".r),
      ("""i am a new yorker""".r),
      ("""im a new yorker""".r),
      ("""i'm a new yorker""".r),
      ("""i am a proud new yorker""".r),
      ("""im a proud new yorker""".r),
      ("""i'm a proud new yorker""".r),
      ("""i'm from new york""".r),
      ("""im from new york""".r),
      ("""i am from new york""".r),
      ("""proud new yorker""".r),
      ("""years old new yorker""".r)
    )

    val africanamericanlist = List (
      ("""ima real nigga""".r),
      ("""young nigga""".r),
      ("""i'm a nigga""".r),
      ("""i am a real nigga""".r),
      ("""im a nigga""".r),
      ("""a nigga like me""".r),
      ("""tall nigga""".r),
      ("""i'm a nigga""".r),
      ("""im a real nigga""".r),
      ("""yung nigga""".r),
      ("""i'm the only nigga""".r),
      ("""im the only nigga""".r),
      ("""i am the only nigga""".r),
      ("""i'm just a lil nigga""".r),
      ("""i am just a lil nigga""".r),
      ("""im just a lil nigga""".r),
      ("""i am a nigga""".r),
      ("""i am a real nigga""".r),
      ("""im a real nigga""".r),
      ("""i am a hating ass nigga""".r),
      ("""im a hating ass nigga""".r),
      ("""i'm a hating ass nigga""".r),
      ("""im the nigga""".r),
      ("""i'm the nigga""".r),
      ("""i am the nigga""".r),
      ("""i am that nigga""".r),
      ("""i'm that nigga""".r),
      ("""im that nigga""".r),
      ("""i'm a real nigga""".r),
      ("""im a true nigga""".r),
      ("""i am a true nigga""".r),
      ("""i'm a true nigga""".r),
      ("""years old nigga""".r),
      ("""proud nigga""".r),
      ("""lazy nigga""".r),
      ("""rich nigga""".r),
      ("""rich ass nigga""".r),
      ("""poor nigga""".r),
      ("""poor ass nigga""".r),
      ("""the best nigga""".r),
      ("""im a westside nigga""".r),
      ("""im a northside nigga""".r),
      ("""cool ass nigga""".r),
      ("""im dat nigga""".r),
      ("""i am dat nigga""".r),
      ("""i'm dat nigga""".r),
      ("""black nigga""".r),
      ("""self made nigga""".r),
      ("""nigga with an attitude""".r),
      ("""im the type of nigga""".r),
      ("""i am the type of nigga""".r),
      ("""i'm the type of nigga""".r),
      ("""just a nigga""".r),
      ("""brown nigga""".r),
      ("""fat nigga""".r),
      ("""skinny nigga""".r),
      ("""slim ass nigga""".r),
      ("""im yo nigga""".r),
      ("""i am yo nigga""".r),
      ("""i'm yo nigga""".r),
      ("""young fly nigga""".r),
      ("""years old nigga""".r),
      ("""years of age nigga""".r),
      ("""i'm an ugly nigga""".r),
      ("""im an ugly nigga""".r),
      ("""i am an ugly nigga""".r),
      ("""just an ugly nigga""".r),
      ("""black nigga""".r)
    )


    val hispaniclist = List (
      ("""i am hispanic""".r),
      ("""im hispanic""".r),
      ("""i'm hispanic""".r),
      ("""i am a hispanic""".r),
      ("""im a hispanic""".r),
      ("""i'm a hispanic""".r),
      ("""i am a proud hispanic""".r),
      ("""im a proud hispanic""".r),
      ("""i'm a proud hispanic""".r),
      ("""proud hispanic""".r),
      ("""years old hispanic""".r),
      ("""i am latina""".r),
      ("""im latina""".r),
      ("""i'm latina""".r),
      ("""i am a latina""".r),
      ("""im a latina""".r),
      ("""i'm a latina""".r),
      ("""i am a proud latina""".r),
      ("""im a proud latina""".r),
      ("""i'm a proud latina""".r),
      ("""proud latina""".r),
      ("""years old latina""".r),
      ("""i am latino""".r),
      ("""im latino""".r),
      ("""i'm latino""".r),
      ("""i am a latino""".r),
      ("""im a latino""".r),
      ("""i'm a latino""".r),
      ("""i am a proud latino""".r),
      ("""im a proud latino""".r),
      ("""i'm a proud latino""".r),
      ("""proud latino""".r),
      ("""years old latino""".r)
    )

    val middleeasternlist = List (
      ("""i love allah""".r),
      ("""the quran""".r),
      ("""the qur'an""".r),
      ("""i am a muslim""".r),
      ("""im a muslim""".r),
      ("""i'm a muslim""".r),
      ("""i'm arab""".r),
      ("""im arab""".r),
      ("""i'm an arab""".r),
      ("""i am arab""".r),
      ("""i am an arab""".r),
      ("""proud arab""".r),
      ("""i am a proud muslim""".r),
      ("""im a proud muslim""".r),
      ("""i'm a proud muslim""".r),
      ("""proud muslim""".r),
      ("""years old muslim""".r),
      ("""i am muslim""".r),
      ("""im pakistani""".r),
      ("""i'm pakistani""".r),
      ("""i am a pakistani""".r),
      ("""im a pakistani""".r),
      ("""i'm a pakistani""".r),
      ("""i am a proud pakistani""".r),
      ("""im a proud pakistani""".r),
      ("""i'm a proud pakistani""".r),
      ("""proud pakistani""".r),
      ("""years old pakistani""".r),
      ("""one allah""".r),
      ("""one rasul""".r),
      ("""one islam""".r),
      ("""one qur'an""".r),
      ("""proud to be a muslim""".r),
      ("""islam is perfect""".r),
      ("""proud of being a muslim""".r),
      ("""i am from pakistan""".r),
      ("""im from pakistan""".r),
      ("""i'm from pakistan""".r),
      ("""i am from the UAE""".r),
      ("""im from the UAE""".r),
      ("""i'm from the UAE""".r)
    )

    val asianlist = List (
      ("""i am asian""".r),
      ("""im asian""".r),
      ("""i'm asian""".r),
      ("""i am a asian""".r),
      ("""im a asian""".r),
      ("""i'm a asian""".r),
      ("""i am a proud asian""".r),
      ("""im a proud asian""".r),
      ("""i'm a proud asian""".r),
      ("""proud asian""".r),
      ("""years old asian""".r),
      ("""i am chinese""".r),
      ("""im chinese""".r),
      ("""i'm chinese""".r),
      ("""i am a chinese""".r),
      ("""im a chinese""".r),
      ("""i'm a chinese""".r),
      ("""i am a proud chinese""".r),
      ("""im a proud chinese""".r),
      ("""i'm a proud chinese""".r),
      ("""proud chinese""".r),
      ("""years old chinese""".r),
      ("""i am indian""".r),
      ("""im indian""".r),
      ("""i'm indian""".r),
      ("""i am a indian""".r),
      ("""im a indian""".r),
      ("""i'm a indian""".r),
      ("""i am a proud indian""".r),
      ("""im a proud indian""".r),
      ("""i'm a proud indian""".r),
      ("""proud indian""".r),
      ("""years old indian""".r),
      ("""i am thai""".r),
      ("""im thai""".r),
      ("""i'm thai""".r),
      ("""i am a thai""".r),
      ("""im a thai""".r),
      ("""i'm a thai""".r),
      ("""i am a proud thai""".r),
      ("""im a proud thai""".r),
      ("""i'm a proud thai""".r),
      ("""proud thai""".r),
      ("""years old thai""".r),
      ("""i am from china""".r),
      ("""im from china""".r),
      ("""i'm from china""".r),
      ("""i am from india""".r),
      ("""im from india""".r),
      ("""i'm from india""".r),
      ("""i am from thailand""".r),
      ("""im from thailand""".r),
      ("""i'm from thailand""".r),
      ("""i am from the phillipines""".r),
      ("""im from the phillipines""".r),
      ("""i'm from the phillipines""".r),
      ("""i am from singapore""".r),
      ("""im from singapore""".r),
      ("""i'm from singapore""".r),
      ("""i am from korea""".r),
      ("""im from korea""".r),
      ("""i'm from korea""".r),
      ("""i am from hong kong""".r),
      ("""im from hong kong""".r),
      ("""i'm from hong kong""".r),
      ("""i am from cambodia""".r),
      ("""im from cambodia""".r),
      ("""i'm from cambodia""".r),
      ("""i am from malaysia""".r),
      ("""im from malaysia""".r),
      ("""i'm from malaysia""".r),
      ("""i am from indonesia""".r),
      ("""im from indonesia""".r),
      ("""i'm from indonesia""".r)
    )

    val australianlist = List (
      ("""i am australian""".r),
      ("""im australian""".r),
      ("""i'm australian""".r),
      ("""i am a australian""".r),
      ("""im a australian""".r),
      ("""i'm a australian""".r),
      ("""i am a proud australian""".r),
      ("""im a proud australian""".r),
      ("""i'm a proud australian""".r),
      ("""proud australian""".r),
      ("""years old australian""".r),
      ("""i am from australia""".r),
      ("""im from australia""".r),
      ("""i'm from australia""".r),
      ("""i am aussie""".r),
      ("""im aussie""".r),
      ("""i'm aussie""".r),
      ("""i am a aussie""".r),
      ("""im a aussie""".r),
      ("""i'm a aussie""".r),
      ("""i am a proud aussie""".r),
      ("""im a proud aussie""".r),
      ("""i'm a proud aussie""".r),
      ("""proud aussie""".r),
      ("""years old aussie""".r),
      ("""i am from aussie""".r),
      ("""im from aussie""".r),
      ("""i'm from aussie""".r)
    )

    val nativeamericanlist = List (
      ("""i am native american""".r),
      ("""im native american""".r),
      ("""i'm native american""".r),
      ("""i am a native american""".r),
      ("""im a native american""".r),
      ("""i'm a native american""".r),
      ("""i am a proud native american""".r),
      ("""im a proud native american""".r),
      ("""i'm a proud native american""".r),
      ("""proud native american""".r),
      ("""years old native american""".r)
    )

    val regex_list = List(
      ("RUSSIAN", russianlist),
      ("MEXICAN", mexicanlist),
      ("AMERICAN", americanlist),
      ("HISPANIC", hispaniclist),
      ("MIDDLEEASTERN", middleeasternlist),
      ("ASIAN", asianlist),
      ("AUSTRALIAN", australianlist),
      ("NATIVEAMERICAN", nativeamericanlist),
      ("AFRICANAMERICAN", africanamericanlist)
    )



    val ans = regex_list.map(elem => (elem._1,
      elem._2.map(reg => reg.findFirstIn(description.toLowerCase).nonEmpty).reduce(_||_))
    ).filter(_._2)

    if (ans.length > 1 || ans.length < 1)
      null
    else
      ans.head._1
  }

}
